<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAJAL-PC" ignored="0" name="POC_Test1" tests="1" failures="0" timestamp="28 Feb 2022 10:29:31 GMT" time="0.209" errors="0">
  <testcase name="@BeforeClass launchApp" time="0.062" classname="com.tyss.demo.baseutil.BaseTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.tyss.demo.baseutil.BaseTest.launchApp(BaseTest.java:120)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass launchApp -->
  <testcase name="@BeforeMethod setExtentReport" time="0.003" classname="com.tyss.demo.baseutil.BaseTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setExtentReport -->
  <testcase name="testDemo" time="0.001" classname="com.tyss.demo.scripts.modulename.Demo">
    <skipped/>
  </testcase> <!-- testDemo -->
</testsuite> <!-- POC_Test1 -->
